// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD39wjCyVhREG-jDTJrA5e91n-COzeJFAo',
    appId: '1:1031006838562:web:25198dcea31c571e6b0f7b',
    messagingSenderId: '1031006838562',
    projectId: 'chat-app-5fc04',
    authDomain: 'chat-app-5fc04.firebaseapp.com',
    storageBucket: 'chat-app-5fc04.appspot.com',
    measurementId: 'G-5QMFNQZPLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNo6gfaDuNSSV_xClwFfjRkdhB17BcOTw',
    appId: '1:1031006838562:android:8d63e6d1f9c868066b0f7b',
    messagingSenderId: '1031006838562',
    projectId: 'chat-app-5fc04',
    storageBucket: 'chat-app-5fc04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-RPwc6_TrdRBXmEOc9doE2xWGou82jPc',
    appId: '1:1031006838562:ios:442f79c4f344acf26b0f7b',
    messagingSenderId: '1031006838562',
    projectId: 'chat-app-5fc04',
    storageBucket: 'chat-app-5fc04.appspot.com',
    iosClientId: '1031006838562-pgcko8mm3idtqn2354lrr1b1j6dcfkgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-RPwc6_TrdRBXmEOc9doE2xWGou82jPc',
    appId: '1:1031006838562:ios:442f79c4f344acf26b0f7b',
    messagingSenderId: '1031006838562',
    projectId: 'chat-app-5fc04',
    storageBucket: 'chat-app-5fc04.appspot.com',
    iosClientId: '1031006838562-pgcko8mm3idtqn2354lrr1b1j6dcfkgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
